CREATE TABLE books (
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    isbn INTEGER UNIQUE NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    published_year INTEGER NOT NULL
);